export const countryNames: string[] = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Congo",
  "Côte d'Ivoire",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Réunion",
  "Rwanda",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Sao Tome and Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania, the United Republic of",
  "Togo",
  "Tunisia",
  "Uganda",
  "Western Sahara*",
  "Zambia",
  "Zimbabwe",
  "Antarctica",
  "Bouvet Island",
  "French Southern Territories",
  "Heard Island and McDonald Islands",
  "South Georgia and the South Sandwich Islands",
  "Afghanistan",
  "Armenia",
  "Azerbaijan",
  "Bangladesh",
  "Bhutan",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Cambodia",
  "China",
  "Georgia",
  "Hong Kong",
  "India",
  "Indonesia",
  "Japan",
  "Kazakhstan",
  "Korea",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Macao",
  "Malaysia",
  "Maldives",
  "Mongolia",
  "Myanmar",
  "Nepal",
  "Pakistan",
  "Philippines",
  "Singapore",
  "Sri Lanka",
  "Taiwan",
  "Tajikistan",
  "Thailand",
  "Timor-Leste",
  "Turkmenistan",
  "Uzbekistan",
  "Viet Nam",
  "Belize",
  "Costa Rica",
  "El Salvador",
  "Guatemala",
  "Honduras",
  "Mexico",
  "Nicaragua",
  "Panama",
  "Åland Islands",
  "Albania",
  "Andorra",
  "Austria",
  "Belarus",
  "Belgium",
  "Bosnia and Herzegovina",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Estonia",
  "Faroe Islands",
  "Finland",
  "France",
  "Germany",
  "Gibraltar",
  "Greece",
  "Guernsey",
  "Holy See",
  "Hungary",
  "Iceland",
  "Ireland",
  "Isle of Man",
  "Italy",
  "Jersey",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Netherlands",
  "North Macedonia",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russian Federation",
  "San Marino",
  "Serbia",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Turkey",
  "Ukraine",
  "United Kingdom of Great Britain and Northern Ireland",
  "Bahrain",
  "Iran",
  "Iraq",
  "Israel",
  "Jordan",
  "Kuwait",
  "Lebanon",
  "Oman",
  "Palestine, State of",
  "Qatar",
  "Saudi Arabia",
  "Syrian Arab Republic",
  "United Arab Emirates",
  "Yemen",
  "Bermuda",
  "Canada",
  "Greenland",
  "Saint Pierre and Miquelon",
  "United States of America",
  "American Samoa",
  "Australia",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Cook Islands",
  "Fiji",
  "French Polynesia",
  "Guam",
  "Kiribati",
  "Marshall Islands",
  "Micronesia (Federated States of)",
  "Nauru",
  "New Caledonia",
  "New Zealand",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Palau",
  "Papua New Guinea",
  "Pitcairn",
  "Samoa",
  "Solomon Islands",
  "Tokelau",
  "Tonga",
  "Tuvalu",
  "United States Minor Outlying Islands",
  "Vanuatu",
  "Wallis and Futuna",
  "Argentina",
  "Bolivia",
  "Brazil",
  "Chile",
  "Colombia",
  "Ecuador",
  "Falkland Islands",
  "French Guiana",
  "Guyana",
  "Paraguay",
  "Peru",
  "Suriname",
  "Uruguay",
  "Venezuela",
  "Anguilla",
  "Antigua and Barbuda",
  "Aruba",
  "Bahamas",
  "Barbados",
  "Bonaire, Sint Eustatius and Saba",
  "Cayman Islands",
  "Cuba",
  "Curaçao",
  "Dominica",
  "Dominican Republic",
  "Grenada",
  "Guadeloupe",
  "Haiti",
  "Jamaica",
  "Martinique",
  "Montserrat",
  "Puerto Rico",
  "Saint Barthélemy",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Vincent and the Grenadines",
  "Sint Maarten (Dutch part)",
  "Trinidad and Tobago",
  "Turks and Caicos Islands",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
];
